services:
  rancher:
    image: rancher/rancher:v2.9.2
    ports:
      - 80:80
      - 443:443
    environment:
      - CATTLE_BOOTSTRAP_PASSWORD=admin12345678
      # - CATTLE_SYSTEM_DEFAULT_REGISTRY=<YOUR-REGISTRY>
      # - CATTLE_SYSTEM_CATALOG=bundled
    privileged: true
    restart: unless-stopped
    volumes:
      - rancher-data:/var/lib/rancher # rancher 資料庫
      - ./ca-certs:/container/ca-certs # registry 使用的 CA 憑證可以放在這裡
      # 以下三行跟自簽憑證有關
      - ./ssl/rancher.crt:/etc/rancher/ssl/cert.pem # rancher 使用的憑證
      - ./ssl/rancher.key:/etc/rancher/ssl/key.pem # rancher 使用的私鑰
      - ./ca-certs/rootCA.crt:/etc/rancher/ssl/cacerts.pem # 簽發 rancher 憑證的 CA 憑證

volumes:
  rancher-data: