services:
  registry:
    image: registry:2
    restart: always
    ports:
      - 5000:5000
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry # Image storage path
    volumes:
      - ./config:/etc/docker/registry
      - ./data:/registry