apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  type: NodePort
  selector:
    app: example-webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30080
